version: '3.1'
services:
  app:
    container_name: myapp
    image: myapp
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quartzdb
      - POSTGRES_HOST=postgresdb
      - APP_TIMEZONE=Asia/Kolkata
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quartzdb
