apiVersion: v1
kind: ConfigMap
metadata:
  name: hostname-config
data:
  postgres_host: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: myapp
spec:
  replicas: {{ .Values.myapp.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_db
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: {{ .Values.myapp.image }}:{{ .Values.myapp.tag }}
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8081
    targetPort: 8081
    name: management
  selector:
    app: myapp
  type: ClusterIP