apiVersion: v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_root_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_root_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgresdb-configmap
                key: postgres_host
        image: rrishi633/quartzapp:1.1