apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-configmap
data:
  postgres_host: postgresdb-service
  database_name: quartzdb

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-root-username: cG9zdGdyZXMK
  postgres-root-password: cGFzc3dvcmQK